name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['27', '26', '25']
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.24.0'
      - run: rebar3 compile
      - run: rebar3 xref
        if: ${{ matrix.otp == '27' }}
      - run: rebar3 dialyzer
        if: ${{ matrix.otp == '27' }}
